// Generated by gencpp from file robot_handover/position.msg
// DO NOT EDIT!


#ifndef ROBOT_HANDOVER_MESSAGE_POSITION_H
#define ROBOT_HANDOVER_MESSAGE_POSITION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_handover
{
template <class ContainerAllocator>
struct position_
{
  typedef position_<ContainerAllocator> Type;

  position_()
    : rot_x(0.0)
    , rot_y(0.0)
    , rot_z(0.0)
    , rot_w(0.0)
    , pos_x(0.0)
    , pos_y(0.0)
    , pos_z(0.0)  {
    }
  position_(const ContainerAllocator& _alloc)
    : rot_x(0.0)
    , rot_y(0.0)
    , rot_z(0.0)
    , rot_w(0.0)
    , pos_x(0.0)
    , pos_y(0.0)
    , pos_z(0.0)  {
  (void)_alloc;
    }



   typedef double _rot_x_type;
  _rot_x_type rot_x;

   typedef double _rot_y_type;
  _rot_y_type rot_y;

   typedef double _rot_z_type;
  _rot_z_type rot_z;

   typedef double _rot_w_type;
  _rot_w_type rot_w;

   typedef double _pos_x_type;
  _pos_x_type pos_x;

   typedef double _pos_y_type;
  _pos_y_type pos_y;

   typedef double _pos_z_type;
  _pos_z_type pos_z;





  typedef boost::shared_ptr< ::robot_handover::position_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_handover::position_<ContainerAllocator> const> ConstPtr;

}; // struct position_

typedef ::robot_handover::position_<std::allocator<void> > position;

typedef boost::shared_ptr< ::robot_handover::position > positionPtr;
typedef boost::shared_ptr< ::robot_handover::position const> positionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_handover::position_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_handover::position_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_handover::position_<ContainerAllocator1> & lhs, const ::robot_handover::position_<ContainerAllocator2> & rhs)
{
  return lhs.rot_x == rhs.rot_x &&
    lhs.rot_y == rhs.rot_y &&
    lhs.rot_z == rhs.rot_z &&
    lhs.rot_w == rhs.rot_w &&
    lhs.pos_x == rhs.pos_x &&
    lhs.pos_y == rhs.pos_y &&
    lhs.pos_z == rhs.pos_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_handover::position_<ContainerAllocator1> & lhs, const ::robot_handover::position_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_handover

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_handover::position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_handover::position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_handover::position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_handover::position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_handover::position_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_handover::position_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_handover::position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5dad714377f525d376acac08d34233e4";
  }

  static const char* value(const ::robot_handover::position_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5dad714377f525d3ULL;
  static const uint64_t static_value2 = 0x76acac08d34233e4ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_handover::position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_handover/position";
  }

  static const char* value(const ::robot_handover::position_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_handover::position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 rot_x\n"
"float64 rot_y\n"
"float64 rot_z\n"
"float64 rot_w\n"
"float64 pos_x\n"
"float64 pos_y\n"
"float64 pos_z\n"
;
  }

  static const char* value(const ::robot_handover::position_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_handover::position_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rot_x);
      stream.next(m.rot_y);
      stream.next(m.rot_z);
      stream.next(m.rot_w);
      stream.next(m.pos_x);
      stream.next(m.pos_y);
      stream.next(m.pos_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct position_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_handover::position_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_handover::position_<ContainerAllocator>& v)
  {
    s << indent << "rot_x: ";
    Printer<double>::stream(s, indent + "  ", v.rot_x);
    s << indent << "rot_y: ";
    Printer<double>::stream(s, indent + "  ", v.rot_y);
    s << indent << "rot_z: ";
    Printer<double>::stream(s, indent + "  ", v.rot_z);
    s << indent << "rot_w: ";
    Printer<double>::stream(s, indent + "  ", v.rot_w);
    s << indent << "pos_x: ";
    Printer<double>::stream(s, indent + "  ", v.pos_x);
    s << indent << "pos_y: ";
    Printer<double>::stream(s, indent + "  ", v.pos_y);
    s << indent << "pos_z: ";
    Printer<double>::stream(s, indent + "  ", v.pos_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_HANDOVER_MESSAGE_POSITION_H
