set(_CATKIN_CURRENT_PACKAGE "robot_handover")
set(robot_handover_VERSION "0.0.0")
set(robot_handover_MAINTAINER "andreas <andreas@todo.todo>")
set(robot_handover_PACKAGE_FORMAT "2")
set(robot_handover_BUILD_DEPENDS "geometry_msgs" "message_generation" "moveit_commander" "moveit_msgs" "roscpp" "rospy" "std_msgs")
set(robot_handover_BUILD_EXPORT_DEPENDS "geometry_msgs" "moveit_commander" "moveit_msgs" "roscpp" "rospy" "std_msgs")
set(robot_handover_BUILDTOOL_DEPENDS "catkin")
set(robot_handover_BUILDTOOL_EXPORT_DEPENDS )
set(robot_handover_EXEC_DEPENDS "geometry_msgs" "moveit_commander" "moveit_msgs" "roscpp" "rospy" "std_msgs" "message_runtime")
set(robot_handover_RUN_DEPENDS "geometry_msgs" "moveit_commander" "moveit_msgs" "roscpp" "rospy" "std_msgs" "message_runtime")
set(robot_handover_TEST_DEPENDS )
set(robot_handover_DOC_DEPENDS )
set(robot_handover_URL_WEBSITE "")
set(robot_handover_URL_BUGTRACKER "")
set(robot_handover_URL_REPOSITORY "")
set(robot_handover_DEPRECATED "")