# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robot_handover/position.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class position(genpy.Message):
  _md5sum = "5dad714377f525d376acac08d34233e4"
  _type = "robot_handover/position"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 rot_x
float64 rot_y
float64 rot_z
float64 rot_w
float64 pos_x
float64 pos_y
float64 pos_z
"""
  __slots__ = ['rot_x','rot_y','rot_z','rot_w','pos_x','pos_y','pos_z']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       rot_x,rot_y,rot_z,rot_w,pos_x,pos_y,pos_z

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(position, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.rot_x is None:
        self.rot_x = 0.
      if self.rot_y is None:
        self.rot_y = 0.
      if self.rot_z is None:
        self.rot_z = 0.
      if self.rot_w is None:
        self.rot_w = 0.
      if self.pos_x is None:
        self.pos_x = 0.
      if self.pos_y is None:
        self.pos_y = 0.
      if self.pos_z is None:
        self.pos_z = 0.
    else:
      self.rot_x = 0.
      self.rot_y = 0.
      self.rot_z = 0.
      self.rot_w = 0.
      self.pos_x = 0.
      self.pos_y = 0.
      self.pos_z = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7d().pack(_x.rot_x, _x.rot_y, _x.rot_z, _x.rot_w, _x.pos_x, _x.pos_y, _x.pos_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 56
      (_x.rot_x, _x.rot_y, _x.rot_z, _x.rot_w, _x.pos_x, _x.pos_y, _x.pos_z,) = _get_struct_7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7d().pack(_x.rot_x, _x.rot_y, _x.rot_z, _x.rot_w, _x.pos_x, _x.pos_y, _x.pos_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 56
      (_x.rot_x, _x.rot_y, _x.rot_z, _x.rot_w, _x.pos_x, _x.pos_y, _x.pos_z,) = _get_struct_7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7d = None
def _get_struct_7d():
    global _struct_7d
    if _struct_7d is None:
        _struct_7d = struct.Struct("<7d")
    return _struct_7d
